# .github/workflows/ci.yml
name: Test & Lint
on: [push, pull_request]

# ci
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 1 Pull the commit/PR code
      - uses: actions/setup-python@v5 # 2 Install Python 3.10
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt -r requirements-dev.txt # 3 Install the tools
      - run: black --check . # 4 Fail if code is not Black-formatted
      - run: ruff check . # 5 Fail if Ruff finds lint errors
      - run: pytest -q             # 6 unit & integration tests

# cd
deploy:
  needs: quality
  if: github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}-web:latest

